import Head from 'next/head'
import styled from '@emotion/styled'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <Title>HOME</Title>
        </Container>
      </main>
    </>
  )
}

const Container = styled.div`
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`

const Title = styled.p`
  text-align: center;
  font-size: 48px;
  margin-bottom: 40px;
`
